### ISSUE TITLE
SDK doesn't create an App Distribution entry

### ISSUE THREAD

**Issue by michaelayates** [chartbeat-labs/android_sdk#6]
We have integrated both the iOS and Android SDKs into our news application. On testing iOS we notice the very first event we fired toward chartbeat creates an "App" section.  _However_ on testing Android (using compiled sdk version 1.1)  the App section is not created in the console when the first event arrives.

![chartbeatdistribution](https://cloud.githubusercontent.com/assets/3631729/15730369/722e98ca-28af-11e6-86c1-7a19e573ebb5.png)

Interestingly if the App section has been created by firing an iOS event then subsequent Android events do appear in the App section.

**Comment by GiarcEnoredlac** [comment]
We have new versions of the SDK available that should solve this issue.
