### ISSUE TITLE
viewId passed for both ID and title

### ISSUE THREAD

**Issue by michaelayates** [chartbeat-labs/android_sdk#8]
Line 211 of Tracker.java
https://github.com/chartbeat-labs/android_sdk/blob/fb786b58827ef1669e2c9b3326f590886d788de2/sdk/src/main/java/com/chartbeat/androidsdk/Tracker.java#L211

Should probably read:
 intent.putExtra(KEY_VIEW_TITLE, viewTitle);

Especially considering a couple lines above if no viewTitle has been provided viewTitles is set to the viewId.

**Comment by heavi5ide** [comment]
This is fixed now.
